### ISSUE TITLE
为什么会出现这个问题

### ISSUE THREAD

**Issue by Yangyc07** [orclight/jcaptcha#1]
cd C:\Users\Administrator\Desktop\jcaptcha-master\jcaptcha-master; JAVA_HOME=C:\\Java\\jdk1.7.0_21 cmd /c "\"\"C:\\Program Files\\NetBeans 7.4\\java\\maven\\bin\\mvn.bat\" -Dexec.args=\"-classpath %classpath TestCaptchaClient\" -Dexec.executable=java -Dexec.classpathScope=test -Dmaven.ext.class.path=\"C:\\Program Files\\NetBeans 7.4\\java\\maven-nblib\\netbeans-eventspy.jar\" process-classes org.codehaus.mojo:exec-maven-plugin:1.2.1:exec\"\""
Scanning for projects...
                                                                        
------------------------------------------------------------------------
Building jcaptcha 1.0-SNAPSHOT
------------------------------------------------------------------------

--- exec-maven-plugin:1.2.1:exec (default-cli) @ jcaptcha ---
错误: 找不到或无法加载主类 TestCaptchaClient
------------------------------------------------------------------------
BUILD FAILURE
------------------------------------------------------------------------
Total time: 1.359s
Finished at: Wed Mar 07 08:42:35 CST 2018
Final Memory: 5M/15M
------------------------------------------------------------------------
Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project jcaptcha: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by orclight** [comment]
是否maven没有安装

可以按照这个链接试着解决问题：
https://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
